repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=100]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Update this to the latest or intended version
    hooks:
      - id: prettier
        args: ["--print-width", "250"]
        additional_dependencies:
          - prettier@v4.0.0-alpha.8 # Ensure this matches the `rev` version if specific formatting plugins are not needed
          - "@prettier/plugin-xml@0.13.0" # Update plugin versions as necessary

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.3 # Check for the latest version of the ruff-pre-commit hook
    hooks:
      - id: ruff
        args: ["--fix", "--line-length", "250"]
        additional_dependencies: [] # Add any plugins or dependencies if needed
        language_version: "python3"

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
