services:
  # Add as many notebooks as GPUs
  notebook:
    build: .
    env_file: .env
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      - "JUPYTER_PASSWORD=${JUPYTER_PASSWORD}"
    volumes:
      - ./:/src/
      - "${DATAPATH}:/mnt/prior-data"
      
    command: sleep infinity; nvidia-smi; ls /mnt/prior-data/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
