services:
  # Add as many notebooks as GPUs
  notebook:
    build: .
    env_file: .env
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      - "JUPYTER_PASSWORD=${JUPYTER_PASSWORD}"
    volumes:
      - ./:/src/
      - "${DATAPATH}:/mnt/prior-data"

    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

        limits:
          memory: 35G


# pip uninstall -y ssm
# pip install --upgrade --force-reinstall --no-cache-dir numpy cython
# pip install --no-cache-dir --force-reinstall git+https://github.com/vaibrainium/ssm.git
# pip install --upgrade --force-reinstall --no-binary :all: <package>
# pip install -r requirements.txt
