version: "3.9"
services:
  # Add as many notebooks as GPUs
  notebook:
    build: .
    env_file: .env
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      - "JUPYTER_PASSWORD=${JUPYTER_PASSWORD}"
    volumes:
      - ./:/src/
      - D:/DATA:/mnt/data

    # command:     # Already implemented in WalkerLab image by running jupyter in the background
    command: sleep infinity; nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
# volumes:
#   prior_data:
#     driver: local
#     driver_opts:
#       type: cifs
#       o: username=${USER},password=${PASS},uid=1000,gid=1000,vers=3.0
#       device: //tower.wanprc.org/basso/BassoLabShare
