services:
  # Add as many notebooks as GPUs
  notebook:
    build: .
    env_file: .env
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      - "JUPYTER_PASSWORD=${JUPYTER_PASSWORD}"
      - "PATH=/src/.venv/bin:$PATH"
    volumes:
      - ./:/src/
      - "${DATAPATH}:/mnt/prior-data"

    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

        limits:
          memory: 100G
