services:
  # Add as many notebooks as GPUs
  notebook:
    build: .
    env_file: .env
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      - "JUPYTER_PASSWORD=${JUPYTER_PASSWORD}"
    volumes:
      - ./:/src/
      - "${DATAPATH}:/mnt/prior-data"

    command: >
      bash -c "
        mkdir -p /root/.vscode-server/bin &&
        curl -fsSL https://update.code.visualstudio.com/commit:$$COMMIT/server-linux-x64/stable -o /tmp/vscode-server.tar.gz &&
        tar -xz -C /root/.vscode-server/bin --strip-components=1 --one-top-level=$$COMMIT -f /tmp/vscode-server.tar.gz &&
        rm /tmp/vscode-server.tar.gz &&
        pip uninstall -y ssm &&
        pip install --upgrade --force-reinstall --no-cache-dir numpy cython &&
        pip install --no-cache-dir --force-reinstall git+https://github.com/vaibrainium/ssm.git &&
        pip install -r requirements.txt &&
        pip uninstall -y numpy &&
        pip install --no-cache-dir numpy &&
        pip install --upgrade --force-reinstall cython scipy matplotlib pandas &&
        jupyter lab --ip=0.0.0.0 --no-browser --allow-root
      "

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

        limits:
          memory: 35G


# pip uninstall -y ssm
# pip install --upgrade --force-reinstall --no-cache-dir numpy cython
# pip install --no-cache-dir --force-reinstall git+https://github.com/vaibrainium/ssm.git
# pip install --upgrade --force-reinstall --no-binary :all: <package>
# pip install -r requirements.txt
