"""
parameter_recovery.py

Validate the DDM fitting machinery against synthetic data with KNOWN
ground-truth parameters, generated by the same simulator the fitter uses.

Why this exists
---------------
When empirical fits look "off", you cannot tell whether the data, the model,
the objective, or the optimizer is to blame. Recovery removes that ambiguity:
the data are simulated from the model itself, so a perfect fitter must recover
the generating parameters. If it does not, the problem is in the objective or
the optimizer, never in the data or model structure.

It also produces the single most useful diagnostic in this whole pipeline:
the NLL at the TRUTH versus the NLL at the RECOVERED parameters.

  recovered_nll > truth_nll   -> the OPTIMIZER failed: it never reached a
                                 region as good as the truth. Fix DE settings,
                                 refinement, bounds, or n_reps.

  recovered_nll <= truth_nll  -> the OBJECTIVE is the problem: a wrong
   but params differ a lot       parameter set scores as well as or better
                                 than the truth, i.e. the loss is flat / the
                                 parameters are not identifiable under it.
                                 Re-weight terms, add constraints, or drop
                                 parameters.

Usage
-----
    python parameter_recovery.py                 # default: full leak+tc model
    python parameter_recovery.py --n_repeats 10  # 10 synthetic datasets
    python parameter_recovery.py --no_leak --no_tc

Runs CPU-only by default so it can be developed off the cluster; pass
--device cuda to match the production code path exactly.
"""

import argparse
import json
import logging
from pathlib import Path

import numpy as np
import pandas as pd

# Mirror the production imports so we test the EXACT same code path.
from src.ddm.ddm import DecisionModel, FreeParam, FixedParam
from src.ddm.utils import build_stimulus
from src.ddm.simulator import DriftDiffusionSimulator

# Reuse the production model + variant config so recovery exercises the real
# objective and bounds, not a parallel copy that can drift out of sync.
from ddm_fitting import DDMModel, make_params, LIKELIHOOD_PARAMS

# basicConfig is a no-op if any imported module already called it (ddm.py and
# likelihood_calculator.py both do). Force the root logger level and handler
# format so progress lines actually appear regardless of import order.
_root = logging.getLogger()
_root.setLevel(logging.INFO)
if _root.handlers:
    _root.handlers[0].setFormatter(
        logging.Formatter("%(asctime)s | %(levelname)s | %(name)s | %(message)s")
    )
else:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s")
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Ground truth. Every value sits comfortably inside the production bounds in
# ddm_fitting.make_params so a well-behaved fitter has no excuse.
# ---------------------------------------------------------------------------

GROUND_TRUTH = {
    "ndt":           0.30,
    "a":             1.80,
    "z":             0.50,
    "drift_gain":    5.00,
    "drift_offset":  0.00,
    "variance":      1.00,   # fixed in production
    "dt":            0.001,  # fixed in production
    "leak_rate":     0.10,
    "time_constant": 0.20,
    "sv":            0.50,
    "sz":            0.10,
}

# Match the empirical design: 7 signed coherences, balanced, ~N per cell.
COHERENCES = np.array([-0.5, -0.2, -0.07, 0.0, 0.07, 0.2, 0.5])
TRIALS_PER_COH = 55          # ~385 trials, close to one block of one session


# ---------------------------------------------------------------------------
# Synthetic data generation
# ---------------------------------------------------------------------------

def make_ground_truth_data(gt_params: dict, coherences, n_per_coh, seed, device) -> pd.DataFrame:
    """Simulate one dataset from the generating model and return tidy behavior."""
    rng = np.random.default_rng(seed)

    coh_col = np.repeat(coherences, n_per_coh)
    rng.shuffle(coh_col)

    # Generous generation window so even the slow tail crosses. We deliberately
    # do NOT reuse build_stimulus here: the buffer logic is what we want to test
    # downstream, not what we want governing the ground-truth draw.
    gen_len = max(100, int(8.0 / gt_params["dt"]))
    stim = np.tile(coh_col[:, None], (1, gen_len)).astype(np.float32)

    sim = DriftDiffusionSimulator(device=device)
    np.random.seed(seed)          # the simulator's no-CRN path draws via np.random
    import torch
    torch.manual_seed(seed)

    df = sim.simulate_trials(stim, gt_params)
    df = df[np.isfinite(df["rt"]) & np.isfinite(df["choice"])].reset_index(drop=True)
    df["choice"] = df["choice"].astype(int)

    n_dropped = len(coh_col) - len(df)
    if n_dropped > 0:
        logger.info("Generation: %d / %d trials never crossed and were dropped.",
                    n_dropped, len(coh_col))
    return df


# ---------------------------------------------------------------------------
# NLL at an arbitrary parameter set (the truth-vs-recovered diagnostic)
# ---------------------------------------------------------------------------

def nll_at(model: DecisionModel, params: dict, data: pd.DataFrame, stimulus,
           n_reps: int, precomputed: dict | None = None) -> float:
    """Compute the fitting objective at a fixed parameter set.

    Temporarily swaps in `precomputed` (must have at least `n_reps` reps) so the
    evaluation is not bounded by, or coupled to, whatever noise block fit() left
    on the model. Passing the SAME block for the truth and recovered evaluations
    makes their NLLs a common-random-numbers comparison, so the gap reflects the
    parameters, not two different noise draws.
    """
    saved = model._precomputed
    model._precomputed = precomputed
    try:
        sim = model._simulate_condition(stimulus, params, n_reps)
    finally:
        model._precomputed = saved
    if sim is None:
        return float("inf")
    return float(model.likelihood_calc.compute_nll(
        sim["rt"].to_numpy(), sim["choice"].to_numpy(),
        data["rt"].to_numpy(), data["choice"].to_numpy(),
        sim["signed_coherence"].to_numpy(), data["signed_coherence"].to_numpy(),
    ))


# ---------------------------------------------------------------------------
# One recovery run
# ---------------------------------------------------------------------------

def run_once(enable_leak, enable_tc, enable_sv, enable_sz, seed, device,
             n_reps_eval=25, chrono_weight=None, caf_weight=None):
    gt = dict(GROUND_TRUTH)
    # Zero out any parameter the chosen variant holds fixed, so the truth is
    # actually reproducible by that variant.
    if not enable_leak:
        gt["leak_rate"] = 0.0
    if not enable_tc:
        gt["time_constant"] = 0.0
    if not enable_sv:
        gt["sv"] = 0.0
    if not enable_sz:
        gt["sz"] = 0.0

    data = make_ground_truth_data(gt, COHERENCES, TRIALS_PER_COH, seed=seed, device=device)
    stimulus = build_stimulus(data)

    free_params, fixed_params = make_params(enable_leak, enable_tc, enable_sv, enable_sz)

    # Allow overriding the auxiliary-term weights so we can test whether the
    # composite objective (KL + chrono MSE + CAF MSE) is biasing the estimator.
    # Setting both to 0 reduces the objective to the proper KL divergence alone.
    lik = dict(LIKELIHOOD_PARAMS)
    if chrono_weight is not None:
        lik["chrono_weight"] = chrono_weight
    if caf_weight is not None:
        lik["caf_weight"] = caf_weight

    model = DDMModel(fixed_params=fixed_params, free_params=free_params,
                     likelihood_params=lik)
    model.seed = seed

    result = model.fit(
        data=data,
        stimulus=stimulus,
        n_reps=15,
        max_iterations=300,
        l1_weight=0.0,
        verbose=True,
    )
    recovered = result["parameters"]

    # Diagnostic NLLs at a larger, fixed n_reps for a stable comparison.
    # Build a dedicated noise block sized to n_reps_eval (fit() only left a
    # 15-rep block on the model) and reuse it for both evaluations so the
    # truth-vs-recovered gap is a clean common-random-numbers comparison.
    model._set_seed(seed + 99)
    n_trials, n_timepoints = stimulus.shape
    eval_noise = model.simulator.precompute_noise(n_trials, n_timepoints, n_reps=n_reps_eval)

    truth_nll     = nll_at(model, gt,        data, stimulus, n_reps_eval, precomputed=eval_noise)
    recovered_nll = nll_at(model, recovered, data, stimulus, n_reps_eval, precomputed=eval_noise)

    rows = []
    for key in model.fit_keys:
        true_v = gt[key]
        rec_v  = recovered[key]
        lo, hi = free_params[key].lower_bound, free_params[key].upper_bound
        denom  = (hi - lo) if (hi - lo) > 0 else 1.0
        rows.append({
            "param": key,
            "true": true_v,
            "recovered": rec_v,
            "abs_err": abs(rec_v - true_v),
            "norm_err": abs(rec_v - true_v) / denom,   # error as fraction of bound width
        })

    return {
        "seed": seed,
        "truth_nll": truth_nll,
        "recovered_nll": recovered_nll,
        "optimizer_gap": recovered_nll - truth_nll,    # >0 means optimizer fell short
        "n_data_trials": len(data),
        "params": rows,
    }


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def print_run(run):
    print(f"\n=== seed {run['seed']} | {run['n_data_trials']} trials ===")
    print(f"{'param':<14}{'true':>10}{'recovered':>12}{'abs_err':>10}{'norm_err':>10}")
    for r in run["params"]:
        print(f"{r['param']:<14}{r['true']:>10.3f}{r['recovered']:>12.3f}"
              f"{r['abs_err']:>10.3f}{r['norm_err']:>10.3f}")
    print(f"{'NLL @ truth':<14}{run['truth_nll']:>10.2f}")
    print(f"{'NLL @ recov':<14}{run['recovered_nll']:>10.2f}")
    gap = run["optimizer_gap"]
    if gap > 1.0:
        verdict = "OPTIMIZER fell short of truth (tune DE / refinement / n_reps)"
    elif gap < -1.0:
        verdict = "OBJECTIVE prefers wrong params (identifiability / weighting)"
    else:
        verdict = "truth and recovered score equally (good optimizer; check param errors)"
    print(f"{'gap':<14}{gap:>10.2f}   -> {verdict}")


def summarize(runs):
    print("\n\n========== RECOVERY SUMMARY ==========")
    keys = [r["param"] for r in runs[0]["params"]]
    print(f"{'param':<14}{'mean|err|':>12}{'mean norm_err':>16}{'max norm_err':>14}")
    for k in keys:
        errs  = [next(p for p in run["params"] if p["param"] == k)["abs_err"] for run in runs]
        nerrs = [next(p for p in run["params"] if p["param"] == k)["norm_err"] for run in runs]
        print(f"{k:<14}{np.mean(errs):>12.3f}{np.mean(nerrs):>16.3f}{np.max(nerrs):>14.3f}")

    gaps = np.array([r["optimizer_gap"] for r in runs])
    print(f"\noptimizer gap (recovered_nll - truth_nll): "
          f"mean={gaps.mean():.2f}  min={gaps.min():.2f}  max={gaps.max():.2f}")
    print("  positive  -> optimizer is the bottleneck")
    print("  ~zero     -> optimizer fine; large param errors then mean weak identifiability")
    print("  negative  -> objective rewards the wrong parameters")
    # A rough pass/fail on identifiability: every param within 15% of its bound width.
    worst = max(max(p["norm_err"] for p in run["params"]) for run in runs)
    print(f"\nworst normalized parameter error across all runs: {worst:.3f}")
    print("PASS" if worst < 0.15 else "REVIEW (a parameter is poorly recovered)")


def main():
    ap = argparse.ArgumentParser(description="DDM parameter recovery check")
    ap.add_argument("--n_repeats", type=int, default=5)
    ap.add_argument("--base_seed", type=int, default=1000)
    ap.add_argument("--device", type=str, default="cpu", choices=["cpu", "cuda"])
    ap.add_argument("--no_leak", action="store_true")
    ap.add_argument("--no_tc", action="store_true")
    ap.add_argument("--no_sv", action="store_true")
    ap.add_argument("--no_sz", action="store_true")
    ap.add_argument("--chrono_weight", type=float, default=None,
                    help="Override chrono_weight (set 0 to test pure-KL objective).")
    ap.add_argument("--caf_weight", type=float, default=None,
                    help="Override caf_weight (set 0 to test pure-KL objective).")
    ap.add_argument("--out", type=str, default="recovery_results.json")
    args = ap.parse_args()

    enable_leak = not args.no_leak
    enable_tc   = not args.no_tc
    enable_sv   = not args.no_sv
    enable_sz   = not args.no_sz

    logger.info("Variant: leak=%s tc=%s sv=%s sz=%s | device=%s | repeats=%d",
                enable_leak, enable_tc, enable_sv, enable_sz, args.device, args.n_repeats)

    runs = []
    for i in range(args.n_repeats):
        run = run_once(enable_leak, enable_tc, enable_sv, enable_sz,
                       seed=args.base_seed + i, device=args.device,
                       chrono_weight=args.chrono_weight, caf_weight=args.caf_weight)
        print_run(run)
        runs.append(run)

    summarize(runs)

    Path(args.out).write_text(json.dumps(runs, indent=2, default=float))
    logger.info("Wrote %s", args.out)


if __name__ == "__main__":
    main()
