rejection_criteria: 
  multi_saccade:
    onset_event: "saccade" # eye data aligned on response onset from timestamp
    pre_onset_duration: 100 # ms
    post_onset_duration: 75 # ms, we will look at the eye data from -pre_saccade_onset_duration to post_onset_duration after saccade onset to determine if it's a multi-saccade trial
    percent_target_threshold: 0.75 # if the eye reaches this percentage of the target, then we consider it as a valid trial, otherwise we consider it as a multi-saccade trial and exclude it
    fixation_window_radius: 1 # degree visual angle
    
    
  anticipatory_saccade:
    onset_event: "go" # eye data aligned on go cue from timestamp
    pre_onset_duration: 200 # ms
    post_onset_duration: 90 # ms, we will look at the eye data from pre_onset_duration before go cue to post_onset_duration after go cue to determine if it's an anticipatory saccade trial
    amplitude_threshold: 2.5 # degree visual angle, if the eye moves more than it during the anticipatory time window, then we consider it as an anticipatory saccade trial and exclude it

  psychometric_function: 
    mean_threshold: 4
    var_threshold: 0.03

GLM_HMM:
  name: "masked_no_bias_1_back_prev_choice_coherence"
  observed_dimensions: 1
  n_categories: 2
  add_bias: false
  current_trial_features: ["normalized_stimulus"]
  prev_trial_features:
    ["prev_choice", "prev_coherence", "prev_choice_coherence"]
  flip_columns: ["normalized_stimulus", "prev_choice", "prev_coherence"]
  n_trials_back: 1

colors:
  prior_colors:
    equal: "#000000"
    L: "#F781BF"
    R: "#4DAF4A"
  block_colors:
    equal: "#A65628"
    unequal: "#984EA3"
  state_colors:
    biased: "#1f77b4"
    unbiased: "#ff7f0e"
